@url = https://localhost:5001

### CREATE new company
POST {{url}}/company/create
Content-Type: application/json

{
    "name": "nowa firma3",
    "establishmentYear": 2019,
    "employees": 
    [
        {
            "firstName": "imie3",
            "lastName": "nazwisko3",
            "dateOfBirth": "2012-03-21T00:00Z",
            "jobTitle": "Manager"
        },
    ]
}


### SEARCH companies
POST {{url}}/company/search
Content-Type: application/json

{
    "keyword": "nowa",
    "employeeDateOfBirthFrom": "2000-03-20",
    "employeeDateOfBirthTo": "2020-01-01",
    "employeeJobTitles": ["Manager"]
}