@url = https://localhost:5001
@token = QWRtaW46U2VjcmV0
@comapnyId = #--CompanyId--#

### CREATE new company
POST {{url}}/company/create
Authorization: Basic {{token}}
Content-Type: application/json

{
    "name": "Pumox",
    "establishmentYear": 2000,
    "employees": 
    [
        {
            "firstName": "Tomasz",
            "lastName": "Klag",
            "dateOfBirth": "1992-01-03",
            "jobTitle": "Developer"
        },
    ]
}


### SEARCH companies
POST {{url}}/company/search
Content-Type: application/json

{
    "keyword": "Pumox",
    "employeeDateOfBirthFrom": "2000-01-01",
    "employeeDateOfBirthTo": "2020-01-01",
    "employeeJobTitles": ["Developer", "Manager"]
}


### UPDATE company by id
PUT {{url}}/company/update/{{comapnyId}}
Authorization: Basic {{token}}
Content-Type: application/json

{
    "name": "Pumox",
    "establishmentYear": 2000,
    "employees": 
    [
        {
            "firstName": "Tomasz",
            "lastName": "Klag",
            "dateOfBirth": "1992-01-03",
            "jobTitle": "Developer"
        },
        {
            "firstName": "Mikoaj",
            "lastName": "Kopernik",
            "dateOfBirth": "1473-02-19",
            "jobTitle": "Manager"
        }
    ]
}

### DELETE company by id
DELETE {{url}}/company/delete/{{comapnyId}}
Authorization: Basic {{token}}